name: publish
on:
  push:
    branches: [main]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - run: npm ci
      # Install @angular/cli
      - run: npm install -g @angular/cli
      # Build the project
      - run: ng build --project ngx-list-search
      # Publish the project
      - run: npm install -g @jsdevtools/npm-publish
      - name: Publish to npm
        working-directory: ./dist/ngx-list-search
        run: npm-publish --token={{secrets.NPM_TOKEN}}
